### ISSUE TITLE
stuff to do wednesday

### ISSUE THREAD

**Issue by mikedagoat** [mikedagoat/mystuffs#7]
- [ ]  chapter of new booky
 - [x] look through school work
 - [x] look at the school's blog
 - [x] do homework mat
 - [x] do sumdog

**Comment by wwaites** [comment]
The Clàs 7 blog is here: http://www.taobhnapairce.edin.sch.uk/index.php/category/c7/

**Comment by wwaites** [comment]
more stuff, from tnp:

  - [x] read chapter of Sraid na h-Eala
  - [x] read 2 sections of Beanntan Pheru
  - [x] algebraic thinking
    - [x] p4 number sequences
    - [ ] p5 fraction sequences
  - [ ] L1 Leabhar Leudachaidh
  - [ ] get set up with school email

**Comment by mikedagoat** [comment]
i will do p5 fraction sequences today and i am waiting for a dictionary so i cant do L1 leabhar leudachaidh and i will get set up with school email tooday
